stages:
  - test

variables:
  PIP_DISABLE_PIP_VERSION_CHECK: '1'
  PYTHONDONTWRITEBYTECODE: '1'
  PYTHONUNBUFFERED: '1'

test:
  stage: test
  image: python:3.11
  script:
    - cd app
    - pip install -r requirements.txt
    - python -m compileall .
